set pages 0;
set linesize 500;
set trimspool on;
set timing off;
set feedback off;
 
spool create_tables.sql
 
SELECT 'CREATE '||DECODE(BIGFILE,'YES','BIGFILE ',NULL)||'TABLESPACE '||TABLESPACE_NAME||
  ' DATAFILE  SIZE 100M AUTOEXTEND ON NEXT 100M EXTENT MANAGEMENT '||EXTENT_MANAGEMENT||
  decode(ALLOCATION_TYPE,'SYSTEM',' AUTOALLOCATE',' UNIFORM','UNIFORM SIZE '||MIN_EXTLEN,NULL)||
  ' SEGMENT SPACE MANAGEMENT '||SEGMENT_SPACE_MANAGEMENT||';'
FROM DBA_TABLESPACES
WHERE CONTENTS='PERMANENT'
  AND TABLESPACE_NAME NOT IN ('SYSTEM','SYSAUX','TOOLS')
  AND TABLESPACE_NAME NOT LIKE 'INDX%'
  AND TABLESPACE_NAME NOT LIKE 'UNDO%'
ORDER BY TABLESPACE_NAME;
 
spool off;
