set pages 0
spool fullexport.par
SELECT USERNAME||',\' FROM (
SELECT USERNAME FROM DBA_USERS
WHERE USERNAME NOT IN ('ANONYMOUS', 'APPQOSSYS', 'CTXSYS', 'DBSNMP', 'DIP', 'ORACLE_OCM', 'OUTLN', 'SYS', 'SYSTEM', 'TRACESVR', 'TSMSYS', 'WMSYS', 'XDB', 'XS$NULL')
AND PROFILE != 'USERS'
UNION ALL
SELECT USERNAME FROM DBA_USERS u WHERE PROFILE = 'USERS'
AND EXISTS (SELECT 1 FROM DBA_OBJECTS WHERE OWNER = u.USERNAME));
spool off
